metrics:
  global:
    scrape_interval: 2s
  configs:
  - name: hosted-prometheus
    scrape_configs:
      - job_name: fhexporter_1
        static_configs:
        - targets: ['localhost:8599']
    remote_write:
      - url: https://prometheus-prod-18-prod-ap-southeast-0.grafana.net/api/prom/push
        basic_auth:
          username: grafana-cloud-user
          password: grafana-cloud-password

